// Code generated by protoc-gen-go. DO NOT EDIT.
// source: team.proto

package team

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TeamUpsertRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Team                 *Team    `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamUpsertRequest) Reset()         { *m = TeamUpsertRequest{} }
func (m *TeamUpsertRequest) String() string { return proto.CompactTextString(m) }
func (*TeamUpsertRequest) ProtoMessage()    {}
func (*TeamUpsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{0}
}

func (m *TeamUpsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamUpsertRequest.Unmarshal(m, b)
}
func (m *TeamUpsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamUpsertRequest.Marshal(b, m, deterministic)
}
func (m *TeamUpsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamUpsertRequest.Merge(m, src)
}
func (m *TeamUpsertRequest) XXX_Size() int {
	return xxx_messageInfo_TeamUpsertRequest.Size(m)
}
func (m *TeamUpsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamUpsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeamUpsertRequest proto.InternalMessageInfo

func (m *TeamUpsertRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *TeamUpsertRequest) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *TeamUpsertRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type TeamUpsertResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamUpsertResponse) Reset()         { *m = TeamUpsertResponse{} }
func (m *TeamUpsertResponse) String() string { return proto.CompactTextString(m) }
func (*TeamUpsertResponse) ProtoMessage()    {}
func (*TeamUpsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{1}
}

func (m *TeamUpsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamUpsertResponse.Unmarshal(m, b)
}
func (m *TeamUpsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamUpsertResponse.Marshal(b, m, deterministic)
}
func (m *TeamUpsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamUpsertResponse.Merge(m, src)
}
func (m *TeamUpsertResponse) XXX_Size() int {
	return xxx_messageInfo_TeamUpsertResponse.Size(m)
}
func (m *TeamUpsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamUpsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TeamUpsertResponse proto.InternalMessageInfo

func (m *TeamUpsertResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *TeamUpsertResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TeamUpsertResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TeamDeleteRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	TeamId               string   `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamDeleteRequest) Reset()         { *m = TeamDeleteRequest{} }
func (m *TeamDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*TeamDeleteRequest) ProtoMessage()    {}
func (*TeamDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{2}
}

func (m *TeamDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamDeleteRequest.Unmarshal(m, b)
}
func (m *TeamDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamDeleteRequest.Marshal(b, m, deterministic)
}
func (m *TeamDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamDeleteRequest.Merge(m, src)
}
func (m *TeamDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_TeamDeleteRequest.Size(m)
}
func (m *TeamDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeamDeleteRequest proto.InternalMessageInfo

func (m *TeamDeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *TeamDeleteRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *TeamDeleteRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type TeamDeleteResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Teams                int64    `protobuf:"varint,3,opt,name=teams,proto3" json:"teams,omitempty"`
	Members              int64    `protobuf:"varint,4,opt,name=members,proto3" json:"members,omitempty"`
	Skills               int64    `protobuf:"varint,5,opt,name=skills,proto3" json:"skills,omitempty"`
	Id                   string   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamDeleteResponse) Reset()         { *m = TeamDeleteResponse{} }
func (m *TeamDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*TeamDeleteResponse) ProtoMessage()    {}
func (*TeamDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{3}
}

func (m *TeamDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamDeleteResponse.Unmarshal(m, b)
}
func (m *TeamDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamDeleteResponse.Marshal(b, m, deterministic)
}
func (m *TeamDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamDeleteResponse.Merge(m, src)
}
func (m *TeamDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_TeamDeleteResponse.Size(m)
}
func (m *TeamDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TeamDeleteResponse proto.InternalMessageInfo

func (m *TeamDeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *TeamDeleteResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TeamDeleteResponse) GetTeams() int64 {
	if m != nil {
		return m.Teams
	}
	return 0
}

func (m *TeamDeleteResponse) GetMembers() int64 {
	if m != nil {
		return m.Members
	}
	return 0
}

func (m *TeamDeleteResponse) GetSkills() int64 {
	if m != nil {
		return m.Skills
	}
	return 0
}

func (m *TeamDeleteResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MemberUpsertRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	TeamId               string   `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	MemberId             string   `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	MemberEmail          string   `protobuf:"bytes,4,opt,name=member_email,json=memberEmail,proto3" json:"member_email,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	UserId               string   `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberUpsertRequest) Reset()         { *m = MemberUpsertRequest{} }
func (m *MemberUpsertRequest) String() string { return proto.CompactTextString(m) }
func (*MemberUpsertRequest) ProtoMessage()    {}
func (*MemberUpsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{4}
}

func (m *MemberUpsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberUpsertRequest.Unmarshal(m, b)
}
func (m *MemberUpsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberUpsertRequest.Marshal(b, m, deterministic)
}
func (m *MemberUpsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberUpsertRequest.Merge(m, src)
}
func (m *MemberUpsertRequest) XXX_Size() int {
	return xxx_messageInfo_MemberUpsertRequest.Size(m)
}
func (m *MemberUpsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberUpsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MemberUpsertRequest proto.InternalMessageInfo

func (m *MemberUpsertRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MemberUpsertRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *MemberUpsertRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *MemberUpsertRequest) GetMemberEmail() string {
	if m != nil {
		return m.MemberEmail
	}
	return ""
}

func (m *MemberUpsertRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *MemberUpsertRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type MemberUpsertResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	MemberNumber         string   `protobuf:"bytes,2,opt,name=member_number,json=memberNumber,proto3" json:"member_number,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberUpsertResponse) Reset()         { *m = MemberUpsertResponse{} }
func (m *MemberUpsertResponse) String() string { return proto.CompactTextString(m) }
func (*MemberUpsertResponse) ProtoMessage()    {}
func (*MemberUpsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{5}
}

func (m *MemberUpsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberUpsertResponse.Unmarshal(m, b)
}
func (m *MemberUpsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberUpsertResponse.Marshal(b, m, deterministic)
}
func (m *MemberUpsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberUpsertResponse.Merge(m, src)
}
func (m *MemberUpsertResponse) XXX_Size() int {
	return xxx_messageInfo_MemberUpsertResponse.Size(m)
}
func (m *MemberUpsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberUpsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MemberUpsertResponse proto.InternalMessageInfo

func (m *MemberUpsertResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MemberUpsertResponse) GetMemberNumber() string {
	if m != nil {
		return m.MemberNumber
	}
	return ""
}

func (m *MemberUpsertResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type MemberDeleteRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	TeamId               string   `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	MemberNumber         string   `protobuf:"bytes,3,opt,name=member_number,json=memberNumber,proto3" json:"member_number,omitempty"`
	MemberEmail          string   `protobuf:"bytes,4,opt,name=member_email,json=memberEmail,proto3" json:"member_email,omitempty"`
	UserId               string   `protobuf:"bytes,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberDeleteRequest) Reset()         { *m = MemberDeleteRequest{} }
func (m *MemberDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*MemberDeleteRequest) ProtoMessage()    {}
func (*MemberDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{6}
}

func (m *MemberDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberDeleteRequest.Unmarshal(m, b)
}
func (m *MemberDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberDeleteRequest.Marshal(b, m, deterministic)
}
func (m *MemberDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberDeleteRequest.Merge(m, src)
}
func (m *MemberDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_MemberDeleteRequest.Size(m)
}
func (m *MemberDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MemberDeleteRequest proto.InternalMessageInfo

func (m *MemberDeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MemberDeleteRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *MemberDeleteRequest) GetMemberNumber() string {
	if m != nil {
		return m.MemberNumber
	}
	return ""
}

func (m *MemberDeleteRequest) GetMemberEmail() string {
	if m != nil {
		return m.MemberEmail
	}
	return ""
}

func (m *MemberDeleteRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type MemberDeleteResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberDeleteResponse) Reset()         { *m = MemberDeleteResponse{} }
func (m *MemberDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*MemberDeleteResponse) ProtoMessage()    {}
func (*MemberDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{7}
}

func (m *MemberDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberDeleteResponse.Unmarshal(m, b)
}
func (m *MemberDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberDeleteResponse.Marshal(b, m, deterministic)
}
func (m *MemberDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberDeleteResponse.Merge(m, src)
}
func (m *MemberDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_MemberDeleteResponse.Size(m)
}
func (m *MemberDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MemberDeleteResponse proto.InternalMessageInfo

func (m *MemberDeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MemberDeleteResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MemberDeleteResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ProjectUpsertRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	TeamId               string   `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	UserId               string   `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectUpsertRequest) Reset()         { *m = ProjectUpsertRequest{} }
func (m *ProjectUpsertRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectUpsertRequest) ProtoMessage()    {}
func (*ProjectUpsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{8}
}

func (m *ProjectUpsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectUpsertRequest.Unmarshal(m, b)
}
func (m *ProjectUpsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectUpsertRequest.Marshal(b, m, deterministic)
}
func (m *ProjectUpsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectUpsertRequest.Merge(m, src)
}
func (m *ProjectUpsertRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectUpsertRequest.Size(m)
}
func (m *ProjectUpsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectUpsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectUpsertRequest proto.InternalMessageInfo

func (m *ProjectUpsertRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *ProjectUpsertRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ProjectUpsertRequest) GetTeamId() string {
	if m != nil {
		return m.TeamId
	}
	return ""
}

func (m *ProjectUpsertRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type ProjectUpsertResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectUpsertResponse) Reset()         { *m = ProjectUpsertResponse{} }
func (m *ProjectUpsertResponse) String() string { return proto.CompactTextString(m) }
func (*ProjectUpsertResponse) ProtoMessage()    {}
func (*ProjectUpsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{9}
}

func (m *ProjectUpsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectUpsertResponse.Unmarshal(m, b)
}
func (m *ProjectUpsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectUpsertResponse.Marshal(b, m, deterministic)
}
func (m *ProjectUpsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectUpsertResponse.Merge(m, src)
}
func (m *ProjectUpsertResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectUpsertResponse.Size(m)
}
func (m *ProjectUpsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectUpsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectUpsertResponse proto.InternalMessageInfo

func (m *ProjectUpsertResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ProjectUpsertResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetByTeamNameRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByTeamNameRequest) Reset()         { *m = GetByTeamNameRequest{} }
func (m *GetByTeamNameRequest) String() string { return proto.CompactTextString(m) }
func (*GetByTeamNameRequest) ProtoMessage()    {}
func (*GetByTeamNameRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{10}
}

func (m *GetByTeamNameRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByTeamNameRequest.Unmarshal(m, b)
}
func (m *GetByTeamNameRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByTeamNameRequest.Marshal(b, m, deterministic)
}
func (m *GetByTeamNameRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByTeamNameRequest.Merge(m, src)
}
func (m *GetByTeamNameRequest) XXX_Size() int {
	return xxx_messageInfo_GetByTeamNameRequest.Size(m)
}
func (m *GetByTeamNameRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByTeamNameRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByTeamNameRequest proto.InternalMessageInfo

func (m *GetByTeamNameRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetByTeamNameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetByTeamNameResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Team                 *Team    `protobuf:"bytes,3,opt,name=team,proto3" json:"team,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByTeamNameResponse) Reset()         { *m = GetByTeamNameResponse{} }
func (m *GetByTeamNameResponse) String() string { return proto.CompactTextString(m) }
func (*GetByTeamNameResponse) ProtoMessage()    {}
func (*GetByTeamNameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{11}
}

func (m *GetByTeamNameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByTeamNameResponse.Unmarshal(m, b)
}
func (m *GetByTeamNameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByTeamNameResponse.Marshal(b, m, deterministic)
}
func (m *GetByTeamNameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByTeamNameResponse.Merge(m, src)
}
func (m *GetByTeamNameResponse) XXX_Size() int {
	return xxx_messageInfo_GetByTeamNameResponse.Size(m)
}
func (m *GetByTeamNameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByTeamNameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByTeamNameResponse proto.InternalMessageInfo

func (m *GetByTeamNameResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetByTeamNameResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetByTeamNameResponse) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *GetByTeamNameResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetByUserIdRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByUserIdRequest) Reset()         { *m = GetByUserIdRequest{} }
func (m *GetByUserIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetByUserIdRequest) ProtoMessage()    {}
func (*GetByUserIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{12}
}

func (m *GetByUserIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByUserIdRequest.Unmarshal(m, b)
}
func (m *GetByUserIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByUserIdRequest.Marshal(b, m, deterministic)
}
func (m *GetByUserIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByUserIdRequest.Merge(m, src)
}
func (m *GetByUserIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetByUserIdRequest.Size(m)
}
func (m *GetByUserIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByUserIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByUserIdRequest proto.InternalMessageInfo

func (m *GetByUserIdRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetByUserIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetByUserIdResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Teams                []*Team  `protobuf:"bytes,3,rep,name=teams,proto3" json:"teams,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByUserIdResponse) Reset()         { *m = GetByUserIdResponse{} }
func (m *GetByUserIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetByUserIdResponse) ProtoMessage()    {}
func (*GetByUserIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{13}
}

func (m *GetByUserIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByUserIdResponse.Unmarshal(m, b)
}
func (m *GetByUserIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByUserIdResponse.Marshal(b, m, deterministic)
}
func (m *GetByUserIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByUserIdResponse.Merge(m, src)
}
func (m *GetByUserIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetByUserIdResponse.Size(m)
}
func (m *GetByUserIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByUserIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByUserIdResponse proto.InternalMessageInfo

func (m *GetByUserIdResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetByUserIdResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetByUserIdResponse) GetTeams() []*Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

func (m *GetByUserIdResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetTeamsRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Page                 int64    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit                int64    `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Role                 string   `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	Level                int64    `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	Technology           string   `protobuf:"bytes,6,opt,name=technology,proto3" json:"technology,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTeamsRequest) Reset()         { *m = GetTeamsRequest{} }
func (m *GetTeamsRequest) String() string { return proto.CompactTextString(m) }
func (*GetTeamsRequest) ProtoMessage()    {}
func (*GetTeamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{14}
}

func (m *GetTeamsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeamsRequest.Unmarshal(m, b)
}
func (m *GetTeamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeamsRequest.Marshal(b, m, deterministic)
}
func (m *GetTeamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeamsRequest.Merge(m, src)
}
func (m *GetTeamsRequest) XXX_Size() int {
	return xxx_messageInfo_GetTeamsRequest.Size(m)
}
func (m *GetTeamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeamsRequest proto.InternalMessageInfo

func (m *GetTeamsRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetTeamsRequest) GetPage() int64 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *GetTeamsRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetTeamsRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *GetTeamsRequest) GetLevel() int64 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *GetTeamsRequest) GetTechnology() string {
	if m != nil {
		return m.Technology
	}
	return ""
}

type GetTeamsResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Teams                []*Team  `protobuf:"bytes,2,rep,name=teams,proto3" json:"teams,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetTeamsResponse) Reset()         { *m = GetTeamsResponse{} }
func (m *GetTeamsResponse) String() string { return proto.CompactTextString(m) }
func (*GetTeamsResponse) ProtoMessage()    {}
func (*GetTeamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{15}
}

func (m *GetTeamsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetTeamsResponse.Unmarshal(m, b)
}
func (m *GetTeamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetTeamsResponse.Marshal(b, m, deterministic)
}
func (m *GetTeamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetTeamsResponse.Merge(m, src)
}
func (m *GetTeamsResponse) XXX_Size() int {
	return xxx_messageInfo_GetTeamsResponse.Size(m)
}
func (m *GetTeamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetTeamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetTeamsResponse proto.InternalMessageInfo

func (m *GetTeamsResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetTeamsResponse) GetTeams() []*Team {
	if m != nil {
		return m.Teams
	}
	return nil
}

func (m *GetTeamsResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Team struct {
	Leader               string    `protobuf:"bytes,1,opt,name=leader,proto3" json:"leader,omitempty"`
	Members              []*Member `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OpenRoles            int32     `protobuf:"varint,4,opt,name=open_roles,json=openRoles,proto3" json:"open_roles,omitempty"`
	Skills               []string  `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty"`
	Size                 int32     `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	LastActive           int32     `protobuf:"varint,7,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	Id                   string    `protobuf:"bytes,8,opt,name=id,proto3" json:"id,omitempty"`
	Project              *Project  `protobuf:"bytes,9,opt,name=project,proto3" json:"project,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{16}
}

func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (m *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(m, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *Team) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Team) GetOpenRoles() int32 {
	if m != nil {
		return m.OpenRoles
	}
	return 0
}

func (m *Team) GetSkills() []string {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *Team) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Team) GetLastActive() int32 {
	if m != nil {
		return m.LastActive
	}
	return 0
}

func (m *Team) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Team) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

type Member struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{17}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Member) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Member) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type Project struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Languages            []string `protobuf:"bytes,2,rep,name=languages,proto3" json:"languages,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	GithubLink           string   `protobuf:"bytes,4,opt,name=github_link,json=githubLink,proto3" json:"github_link,omitempty"`
	Complexity           int32    `protobuf:"varint,5,opt,name=complexity,proto3" json:"complexity,omitempty"`
	Duration             int32    `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{18}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Project) GetLanguages() []string {
	if m != nil {
		return m.Languages
	}
	return nil
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetGithubLink() string {
	if m != nil {
		return m.GithubLink
	}
	return ""
}

func (m *Project) GetComplexity() int32 {
	if m != nil {
		return m.Complexity
	}
	return 0
}

func (m *Project) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func init() {
	proto.RegisterType((*TeamUpsertRequest)(nil), "team.TeamUpsertRequest")
	proto.RegisterType((*TeamUpsertResponse)(nil), "team.TeamUpsertResponse")
	proto.RegisterType((*TeamDeleteRequest)(nil), "team.TeamDeleteRequest")
	proto.RegisterType((*TeamDeleteResponse)(nil), "team.TeamDeleteResponse")
	proto.RegisterType((*MemberUpsertRequest)(nil), "team.MemberUpsertRequest")
	proto.RegisterType((*MemberUpsertResponse)(nil), "team.MemberUpsertResponse")
	proto.RegisterType((*MemberDeleteRequest)(nil), "team.MemberDeleteRequest")
	proto.RegisterType((*MemberDeleteResponse)(nil), "team.MemberDeleteResponse")
	proto.RegisterType((*ProjectUpsertRequest)(nil), "team.ProjectUpsertRequest")
	proto.RegisterType((*ProjectUpsertResponse)(nil), "team.ProjectUpsertResponse")
	proto.RegisterType((*GetByTeamNameRequest)(nil), "team.GetByTeamNameRequest")
	proto.RegisterType((*GetByTeamNameResponse)(nil), "team.GetByTeamNameResponse")
	proto.RegisterType((*GetByUserIdRequest)(nil), "team.GetByUserIdRequest")
	proto.RegisterType((*GetByUserIdResponse)(nil), "team.GetByUserIdResponse")
	proto.RegisterType((*GetTeamsRequest)(nil), "team.GetTeamsRequest")
	proto.RegisterType((*GetTeamsResponse)(nil), "team.GetTeamsResponse")
	proto.RegisterType((*Team)(nil), "team.Team")
	proto.RegisterType((*Member)(nil), "team.Member")
	proto.RegisterType((*Project)(nil), "team.Project")
}

func init() { proto.RegisterFile("team.proto", fileDescriptor_8b4e9e93d7b2c6bb) }

var fileDescriptor_8b4e9e93d7b2c6bb = []byte{
	// 941 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdd, 0x6e, 0xdc, 0x44,
	0x18, 0x8d, 0xd7, 0xf6, 0x6e, 0xfc, 0x6d, 0x0a, 0xed, 0x34, 0x69, 0xdc, 0x2d, 0xb4, 0xc1, 0x48,
	0xd0, 0xab, 0x5e, 0x04, 0x89, 0x1b, 0xb8, 0xd9, 0xb6, 0x28, 0x5a, 0x09, 0x56, 0xc8, 0xb4, 0x70,
	0xd7, 0x95, 0xb3, 0xfe, 0xb4, 0x1d, 0xe2, 0xbf, 0xd8, 0xe3, 0x15, 0xe1, 0x96, 0x77, 0x00, 0x89,
	0x3b, 0x1e, 0x80, 0x17, 0xe0, 0xe5, 0x40, 0xf3, 0x63, 0x7b, 0x66, 0x6b, 0xa7, 0x6d, 0xb8, 0x8a,
	0xbf, 0x6f, 0x66, 0xce, 0x9c, 0x39, 0x73, 0xe6, 0x6c, 0x00, 0x18, 0x46, 0xe9, 0x93, 0xa2, 0xcc,
	0x59, 0x4e, 0x1c, 0xfe, 0x1d, 0xbc, 0x82, 0x3b, 0x2f, 0x30, 0x4a, 0x5f, 0x16, 0x15, 0x96, 0x2c,
	0xc4, 0xcb, 0x1a, 0x2b, 0x46, 0x6e, 0x83, 0x1d, 0x15, 0xd4, 0xb7, 0x4e, 0xac, 0xc7, 0x5e, 0xc8,
	0x3f, 0xc9, 0x43, 0x10, 0xd3, 0xfd, 0xd1, 0x89, 0xf5, 0x78, 0x7a, 0x0a, 0x4f, 0x04, 0x0e, 0x5f,
	0x18, 0x8a, 0x3e, 0x39, 0x86, 0x49, 0x5d, 0x61, 0xb9, 0xa2, 0xb1, 0x6f, 0x8b, 0x55, 0x63, 0x5e,
	0x2e, 0xe2, 0x60, 0x09, 0x44, 0xc7, 0xaf, 0x8a, 0x3c, 0xab, 0xb0, 0x67, 0x83, 0x7b, 0x30, 0xae,
	0x58, 0xc4, 0xea, 0x4a, 0x6c, 0xe1, 0x85, 0xaa, 0x22, 0x1f, 0xc0, 0xa8, 0xc5, 0x1c, 0xd1, 0x38,
	0xf8, 0x49, 0xf2, 0x7d, 0x8e, 0x09, 0x32, 0x1c, 0xe6, 0x7b, 0x0c, 0x13, 0xce, 0x8b, 0xf3, 0x51,
	0x78, 0xbc, 0x5c, 0xc4, 0xc3, 0x44, 0x7f, 0xb7, 0x24, 0xd3, 0x06, 0xf9, 0xbd, 0x99, 0x1e, 0x82,
	0xcb, 0xf7, 0xa8, 0x04, 0xae, 0x1d, 0xca, 0x82, 0xf8, 0x30, 0x49, 0x31, 0x3d, 0xc7, 0xb2, 0xf2,
	0x1d, 0xd1, 0x6f, 0x4a, 0x81, 0x73, 0x41, 0x93, 0xa4, 0xf2, 0x5d, 0x31, 0xa0, 0x2a, 0x75, 0xe2,
	0x71, 0x7b, 0xe2, 0xbf, 0x2d, 0xb8, 0xfb, 0x9d, 0x58, 0xf3, 0xb6, 0x4b, 0x1a, 0x3c, 0xf4, 0x03,
	0xf0, 0xe4, 0xae, 0xdd, 0xb1, 0xf7, 0x65, 0x63, 0x11, 0x93, 0x4f, 0xe0, 0x40, 0x0d, 0x62, 0x1a,
	0xd1, 0x44, 0xd0, 0xf4, 0xc2, 0xa9, 0xec, 0x7d, 0xc3, 0x5b, 0x84, 0x80, 0x53, 0xe6, 0x09, 0x0a,
	0xa2, 0x5e, 0x28, 0xbe, 0x75, 0x21, 0xc7, 0x86, 0x90, 0x08, 0x87, 0x26, 0xdd, 0x41, 0x25, 0x3f,
	0x85, 0x5b, 0x6a, 0xe7, 0xac, 0xe6, 0x7f, 0x14, 0x6b, 0x45, 0x67, 0x29, 0x7a, 0x9a, 0xdc, 0xb6,
	0x2e, 0x77, 0xf0, 0x57, 0x2b, 0xcb, 0x8d, 0xbd, 0xf0, 0xc6, 0xfe, 0x76, 0xcf, 0xfe, 0xef, 0x20,
	0x8f, 0x26, 0x85, 0x6b, 0x48, 0xf1, 0x63, 0x23, 0xc5, 0xff, 0x31, 0xd5, 0x3a, 0xaf, 0x33, 0xd6,
	0x98, 0x4a, 0x14, 0xc1, 0x6f, 0x16, 0x1c, 0x7e, 0x5f, 0xe6, 0x3f, 0xe3, 0x9a, 0x99, 0x9e, 0xf8,
	0x1c, 0x26, 0x85, 0xec, 0x0b, 0xf0, 0xe9, 0xe9, 0x2d, 0xf9, 0x52, 0xd5, 0xe4, 0xb0, 0x19, 0x6d,
	0x18, 0x8c, 0x7a, 0x55, 0xb2, 0x87, 0x5e, 0x8c, 0x63, 0x9c, 0x6e, 0x0e, 0x47, 0x3b, 0x24, 0xde,
	0xf7, 0x78, 0xc1, 0xd7, 0x70, 0x78, 0x86, 0xec, 0xe9, 0x15, 0x7f, 0x78, 0xcb, 0x28, 0xbd, 0xe6,
	0x12, 0x09, 0x38, 0x59, 0x94, 0xa2, 0x5a, 0x2f, 0xbe, 0x83, 0x4b, 0x38, 0xda, 0x59, 0x3d, 0x48,
	0x40, 0x3e, 0xaa, 0x51, 0xf3, 0xa8, 0xda, 0x3c, 0xb3, 0x07, 0xf2, 0xac, 0x23, 0xec, 0x18, 0x84,
	0xbf, 0x04, 0x22, 0xb6, 0x7c, 0x29, 0x24, 0x18, 0xa6, 0xbb, 0xb3, 0x5f, 0x70, 0x09, 0x77, 0x8d,
	0x75, 0xef, 0x4c, 0xf4, 0xa4, 0x4b, 0x15, 0x7b, 0x87, 0xa9, 0x4a, 0x98, 0x21, 0xaa, 0x7f, 0x58,
	0xf0, 0xe1, 0x19, 0x32, 0x3e, 0xb5, 0xba, 0x56, 0xd7, 0x22, 0xda, 0x48, 0x5d, 0xed, 0x50, 0x7c,
	0x73, 0xd3, 0x25, 0x34, 0xa5, 0xad, 0xe9, 0x44, 0xd1, 0x86, 0x80, 0xa3, 0x85, 0x00, 0x9f, 0x89,
	0x5b, 0x4c, 0x54, 0x84, 0xc9, 0x82, 0x3c, 0xe4, 0xbf, 0x33, 0xeb, 0xd7, 0x59, 0x9e, 0xe4, 0x9b,
	0x2b, 0x95, 0x0e, 0x5a, 0x27, 0x78, 0x05, 0xb7, 0x3b, 0x62, 0x83, 0x4a, 0xb4, 0x27, 0x1f, 0xbd,
	0xfd, 0xe4, 0x66, 0x34, 0xfc, 0x6b, 0x81, 0xf3, 0x42, 0xdd, 0x62, 0x82, 0x51, 0x8c, 0xa5, 0xc2,
	0x55, 0x15, 0xf9, 0xac, 0x0b, 0x65, 0x09, 0x7e, 0x20, 0xc1, 0xe5, 0x63, 0xed, 0x22, 0xba, 0x31,
	0x9d, 0xdd, 0x99, 0x8e, 0x7c, 0x0c, 0x90, 0x17, 0x98, 0xad, 0xf8, 0xf9, 0xa5, 0xe4, 0x6e, 0xe8,
	0xf1, 0x4e, 0xc8, 0x1b, 0x46, 0xaa, 0xdb, 0x82, 0x93, 0x4c, 0x75, 0x02, 0x4e, 0x45, 0x7f, 0x45,
	0xa1, 0x86, 0x1b, 0x8a, 0x6f, 0xf2, 0x08, 0xa6, 0x49, 0x54, 0xb1, 0x55, 0xb4, 0x66, 0x74, 0x8b,
	0xfe, 0x44, 0x0c, 0x01, 0x6f, 0xcd, 0x45, 0x47, 0x99, 0x61, 0xbf, 0x35, 0x83, 0xf6, 0xbc, 0xbd,
	0xeb, 0x9e, 0x77, 0xf0, 0x14, 0xc6, 0xf2, 0x2c, 0xfc, 0x86, 0x64, 0x6e, 0x49, 0x05, 0x64, 0xa1,
	0xb9, 0xcc, 0x15, 0xc0, 0xcd, 0xdd, 0xda, 0xdd, 0xdd, 0x06, 0xff, 0x58, 0x30, 0x51, 0xc0, 0xe4,
	0x04, 0xa6, 0x31, 0x56, 0xeb, 0x92, 0x16, 0x8c, 0xe6, 0x99, 0xc2, 0xd2, 0x5b, 0xe4, 0x23, 0xf0,
	0x92, 0x28, 0xdb, 0xd4, 0xd1, 0x06, 0xa5, 0xa8, 0x5e, 0xd8, 0x35, 0x7a, 0x85, 0x7c, 0x04, 0xd3,
	0x0d, 0x65, 0xaf, 0xeb, 0xf3, 0x55, 0x42, 0xb3, 0x0b, 0x65, 0x2b, 0x90, 0xad, 0x6f, 0x69, 0x76,
	0xc1, 0x6d, 0xb4, 0xce, 0xd3, 0x22, 0xc1, 0x5f, 0x28, 0xbb, 0x12, 0x0e, 0x73, 0x43, 0xad, 0x43,
	0x66, 0xb0, 0x1f, 0xd7, 0x65, 0x24, 0x18, 0x49, 0x59, 0xdb, 0xfa, 0xf4, 0x4f, 0x17, 0xa6, 0xdc,
	0x02, 0x3f, 0x60, 0xb9, 0xa5, 0x6b, 0x24, 0x73, 0x80, 0x67, 0x25, 0x46, 0x0c, 0x85, 0x2f, 0x8e,
	0x3b, 0x2f, 0x19, 0xf9, 0x39, 0xf3, 0xdf, 0x1c, 0x90, 0xfe, 0x0c, 0xf6, 0x38, 0x84, 0x8c, 0xf1,
	0x5d, 0x08, 0xe3, 0xf7, 0x47, 0x87, 0x30, 0x53, 0x3f, 0xd8, 0x23, 0xcf, 0xc1, 0x9b, 0xc7, 0xb1,
	0xba, 0x99, 0xfb, 0xba, 0xe7, 0x4c, 0x1a, 0xb3, 0xbe, 0xa1, 0x16, 0xe5, 0x0c, 0x0e, 0x42, 0x4c,
	0xf3, 0x2d, 0xf6, 0x01, 0x99, 0x64, 0x66, 0x7d, 0x43, 0x2d, 0xd0, 0x12, 0xee, 0x48, 0x70, 0x4e,
	0xb6, 0xb9, 0xea, 0x99, 0x61, 0x29, 0x93, 0xd7, 0x83, 0xde, 0x31, 0x1d, 0x4f, 0xbd, 0xeb, 0x2e,
	0x93, 0x1b, 0xbc, 0xbe, 0x98, 0x6f, 0xf0, 0x7a, 0x43, 0x3c, 0xd8, 0x23, 0x8b, 0x2e, 0x27, 0x9a,
	0xe4, 0x24, 0xbe, 0xb6, 0xc4, 0x08, 0xe1, 0xd9, 0xfd, 0x9e, 0x11, 0x8d, 0xda, 0x51, 0x07, 0xf5,
	0xac, 0x2e, 0x4b, 0xcc, 0x18, 0x9f, 0x74, 0x53, 0xbc, 0xaf, 0x60, 0xbf, 0xc1, 0x23, 0x47, 0xed,
	0x44, 0x3d, 0x6b, 0x67, 0xf7, 0x76, 0xdb, 0xcd, 0xe2, 0xf3, 0xb1, 0xf8, 0x07, 0xfc, 0x8b, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0xdf, 0x70, 0x93, 0xb7, 0x8e, 0x0b, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TeamServiceClient is the client API for TeamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TeamServiceClient interface {
	CreateTeam(ctx context.Context, in *TeamUpsertRequest, opts ...grpc.CallOption) (*TeamUpsertResponse, error)
	DeleteTeam(ctx context.Context, in *TeamDeleteRequest, opts ...grpc.CallOption) (*TeamDeleteResponse, error)
	AddMember(ctx context.Context, in *MemberUpsertRequest, opts ...grpc.CallOption) (*MemberUpsertResponse, error)
	RemoveMember(ctx context.Context, in *MemberDeleteRequest, opts ...grpc.CallOption) (*MemberDeleteResponse, error)
	UpsertTeamProject(ctx context.Context, in *ProjectUpsertRequest, opts ...grpc.CallOption) (*ProjectUpsertResponse, error)
	GetTeamByTeamName(ctx context.Context, in *GetByTeamNameRequest, opts ...grpc.CallOption) (*GetByTeamNameResponse, error)
	GetTeamsByUserId(ctx context.Context, in *GetByUserIdRequest, opts ...grpc.CallOption) (*GetByUserIdResponse, error)
	GetTeamsByCurrentUser(ctx context.Context, in *GetByUserIdRequest, opts ...grpc.CallOption) (*GetByUserIdResponse, error)
	GetTeams(ctx context.Context, in *GetTeamsRequest, opts ...grpc.CallOption) (*GetTeamsResponse, error)
}

type teamServiceClient struct {
	cc *grpc.ClientConn
}

func NewTeamServiceClient(cc *grpc.ClientConn) TeamServiceClient {
	return &teamServiceClient{cc}
}

func (c *teamServiceClient) CreateTeam(ctx context.Context, in *TeamUpsertRequest, opts ...grpc.CallOption) (*TeamUpsertResponse, error) {
	out := new(TeamUpsertResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/CreateTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) DeleteTeam(ctx context.Context, in *TeamDeleteRequest, opts ...grpc.CallOption) (*TeamDeleteResponse, error) {
	out := new(TeamDeleteResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/DeleteTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) AddMember(ctx context.Context, in *MemberUpsertRequest, opts ...grpc.CallOption) (*MemberUpsertResponse, error) {
	out := new(MemberUpsertResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/AddMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) RemoveMember(ctx context.Context, in *MemberDeleteRequest, opts ...grpc.CallOption) (*MemberDeleteResponse, error) {
	out := new(MemberDeleteResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/RemoveMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) UpsertTeamProject(ctx context.Context, in *ProjectUpsertRequest, opts ...grpc.CallOption) (*ProjectUpsertResponse, error) {
	out := new(ProjectUpsertResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/UpsertTeamProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) GetTeamByTeamName(ctx context.Context, in *GetByTeamNameRequest, opts ...grpc.CallOption) (*GetByTeamNameResponse, error) {
	out := new(GetByTeamNameResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/GetTeamByTeamName", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) GetTeamsByUserId(ctx context.Context, in *GetByUserIdRequest, opts ...grpc.CallOption) (*GetByUserIdResponse, error) {
	out := new(GetByUserIdResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/GetTeamsByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) GetTeamsByCurrentUser(ctx context.Context, in *GetByUserIdRequest, opts ...grpc.CallOption) (*GetByUserIdResponse, error) {
	out := new(GetByUserIdResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/GetTeamsByCurrentUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) GetTeams(ctx context.Context, in *GetTeamsRequest, opts ...grpc.CallOption) (*GetTeamsResponse, error) {
	out := new(GetTeamsResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/GetTeams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeamServiceServer is the server API for TeamService service.
type TeamServiceServer interface {
	CreateTeam(context.Context, *TeamUpsertRequest) (*TeamUpsertResponse, error)
	DeleteTeam(context.Context, *TeamDeleteRequest) (*TeamDeleteResponse, error)
	AddMember(context.Context, *MemberUpsertRequest) (*MemberUpsertResponse, error)
	RemoveMember(context.Context, *MemberDeleteRequest) (*MemberDeleteResponse, error)
	UpsertTeamProject(context.Context, *ProjectUpsertRequest) (*ProjectUpsertResponse, error)
	GetTeamByTeamName(context.Context, *GetByTeamNameRequest) (*GetByTeamNameResponse, error)
	GetTeamsByUserId(context.Context, *GetByUserIdRequest) (*GetByUserIdResponse, error)
	GetTeamsByCurrentUser(context.Context, *GetByUserIdRequest) (*GetByUserIdResponse, error)
	GetTeams(context.Context, *GetTeamsRequest) (*GetTeamsResponse, error)
}

// UnimplementedTeamServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTeamServiceServer struct {
}

func (*UnimplementedTeamServiceServer) CreateTeam(ctx context.Context, req *TeamUpsertRequest) (*TeamUpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeam not implemented")
}
func (*UnimplementedTeamServiceServer) DeleteTeam(ctx context.Context, req *TeamDeleteRequest) (*TeamDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeam not implemented")
}
func (*UnimplementedTeamServiceServer) AddMember(ctx context.Context, req *MemberUpsertRequest) (*MemberUpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMember not implemented")
}
func (*UnimplementedTeamServiceServer) RemoveMember(ctx context.Context, req *MemberDeleteRequest) (*MemberDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMember not implemented")
}
func (*UnimplementedTeamServiceServer) UpsertTeamProject(ctx context.Context, req *ProjectUpsertRequest) (*ProjectUpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertTeamProject not implemented")
}
func (*UnimplementedTeamServiceServer) GetTeamByTeamName(ctx context.Context, req *GetByTeamNameRequest) (*GetByTeamNameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamByTeamName not implemented")
}
func (*UnimplementedTeamServiceServer) GetTeamsByUserId(ctx context.Context, req *GetByUserIdRequest) (*GetByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamsByUserId not implemented")
}
func (*UnimplementedTeamServiceServer) GetTeamsByCurrentUser(ctx context.Context, req *GetByUserIdRequest) (*GetByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamsByCurrentUser not implemented")
}
func (*UnimplementedTeamServiceServer) GetTeams(ctx context.Context, req *GetTeamsRequest) (*GetTeamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeams not implemented")
}

func RegisterTeamServiceServer(s *grpc.Server, srv TeamServiceServer) {
	s.RegisterService(&_TeamService_serviceDesc, srv)
}

func _TeamService_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeamUpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/CreateTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).CreateTeam(ctx, req.(*TeamUpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_DeleteTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeamDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).DeleteTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/DeleteTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).DeleteTeam(ctx, req.(*TeamDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberUpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/AddMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).AddMember(ctx, req.(*MemberUpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/RemoveMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).RemoveMember(ctx, req.(*MemberDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_UpsertTeamProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectUpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).UpsertTeamProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/UpsertTeamProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).UpsertTeamProject(ctx, req.(*ProjectUpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_GetTeamByTeamName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByTeamNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).GetTeamByTeamName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/GetTeamByTeamName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).GetTeamByTeamName(ctx, req.(*GetByTeamNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_GetTeamsByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).GetTeamsByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/GetTeamsByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).GetTeamsByUserId(ctx, req.(*GetByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_GetTeamsByCurrentUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).GetTeamsByCurrentUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/GetTeamsByCurrentUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).GetTeamsByCurrentUser(ctx, req.(*GetByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_GetTeams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).GetTeams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/GetTeams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).GetTeams(ctx, req.(*GetTeamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TeamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "team.TeamService",
	HandlerType: (*TeamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTeam",
			Handler:    _TeamService_CreateTeam_Handler,
		},
		{
			MethodName: "DeleteTeam",
			Handler:    _TeamService_DeleteTeam_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _TeamService_AddMember_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _TeamService_RemoveMember_Handler,
		},
		{
			MethodName: "UpsertTeamProject",
			Handler:    _TeamService_UpsertTeamProject_Handler,
		},
		{
			MethodName: "GetTeamByTeamName",
			Handler:    _TeamService_GetTeamByTeamName_Handler,
		},
		{
			MethodName: "GetTeamsByUserId",
			Handler:    _TeamService_GetTeamsByUserId_Handler,
		},
		{
			MethodName: "GetTeamsByCurrentUser",
			Handler:    _TeamService_GetTeamsByCurrentUser_Handler,
		},
		{
			MethodName: "GetTeams",
			Handler:    _TeamService_GetTeams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "team.proto",
}
