// Code generated by protoc-gen-go. DO NOT EDIT.
// source: team.proto

package team

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TeamUpsertRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Team                 *Team    `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamUpsertRequest) Reset()         { *m = TeamUpsertRequest{} }
func (m *TeamUpsertRequest) String() string { return proto.CompactTextString(m) }
func (*TeamUpsertRequest) ProtoMessage()    {}
func (*TeamUpsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{0}
}

func (m *TeamUpsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamUpsertRequest.Unmarshal(m, b)
}
func (m *TeamUpsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamUpsertRequest.Marshal(b, m, deterministic)
}
func (m *TeamUpsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamUpsertRequest.Merge(m, src)
}
func (m *TeamUpsertRequest) XXX_Size() int {
	return xxx_messageInfo_TeamUpsertRequest.Size(m)
}
func (m *TeamUpsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamUpsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeamUpsertRequest proto.InternalMessageInfo

func (m *TeamUpsertRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *TeamUpsertRequest) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

type TeamUpsertResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamUpsertResponse) Reset()         { *m = TeamUpsertResponse{} }
func (m *TeamUpsertResponse) String() string { return proto.CompactTextString(m) }
func (*TeamUpsertResponse) ProtoMessage()    {}
func (*TeamUpsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{1}
}

func (m *TeamUpsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamUpsertResponse.Unmarshal(m, b)
}
func (m *TeamUpsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamUpsertResponse.Marshal(b, m, deterministic)
}
func (m *TeamUpsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamUpsertResponse.Merge(m, src)
}
func (m *TeamUpsertResponse) XXX_Size() int {
	return xxx_messageInfo_TeamUpsertResponse.Size(m)
}
func (m *TeamUpsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamUpsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TeamUpsertResponse proto.InternalMessageInfo

func (m *TeamUpsertResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *TeamUpsertResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TeamUpsertResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TeamDeleteRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamDeleteRequest) Reset()         { *m = TeamDeleteRequest{} }
func (m *TeamDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*TeamDeleteRequest) ProtoMessage()    {}
func (*TeamDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{2}
}

func (m *TeamDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamDeleteRequest.Unmarshal(m, b)
}
func (m *TeamDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamDeleteRequest.Marshal(b, m, deterministic)
}
func (m *TeamDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamDeleteRequest.Merge(m, src)
}
func (m *TeamDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_TeamDeleteRequest.Size(m)
}
func (m *TeamDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TeamDeleteRequest proto.InternalMessageInfo

func (m *TeamDeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *TeamDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type TeamDeleteResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Teams                int64    `protobuf:"varint,3,opt,name=teams,proto3" json:"teams,omitempty"`
	Members              int64    `protobuf:"varint,4,opt,name=members,proto3" json:"members,omitempty"`
	Skills               int64    `protobuf:"varint,5,opt,name=skills,proto3" json:"skills,omitempty"`
	Id                   string   `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamDeleteResponse) Reset()         { *m = TeamDeleteResponse{} }
func (m *TeamDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*TeamDeleteResponse) ProtoMessage()    {}
func (*TeamDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{3}
}

func (m *TeamDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamDeleteResponse.Unmarshal(m, b)
}
func (m *TeamDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamDeleteResponse.Marshal(b, m, deterministic)
}
func (m *TeamDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamDeleteResponse.Merge(m, src)
}
func (m *TeamDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_TeamDeleteResponse.Size(m)
}
func (m *TeamDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TeamDeleteResponse proto.InternalMessageInfo

func (m *TeamDeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *TeamDeleteResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *TeamDeleteResponse) GetTeams() int64 {
	if m != nil {
		return m.Teams
	}
	return 0
}

func (m *TeamDeleteResponse) GetMembers() int64 {
	if m != nil {
		return m.Members
	}
	return 0
}

func (m *TeamDeleteResponse) GetSkills() int64 {
	if m != nil {
		return m.Skills
	}
	return 0
}

func (m *TeamDeleteResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type MemberUpsertRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	MemberId             string   `protobuf:"bytes,3,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	MemberEmail          string   `protobuf:"bytes,4,opt,name=member_email,json=memberEmail,proto3" json:"member_email,omitempty"`
	Role                 string   `protobuf:"bytes,5,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberUpsertRequest) Reset()         { *m = MemberUpsertRequest{} }
func (m *MemberUpsertRequest) String() string { return proto.CompactTextString(m) }
func (*MemberUpsertRequest) ProtoMessage()    {}
func (*MemberUpsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{4}
}

func (m *MemberUpsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberUpsertRequest.Unmarshal(m, b)
}
func (m *MemberUpsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberUpsertRequest.Marshal(b, m, deterministic)
}
func (m *MemberUpsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberUpsertRequest.Merge(m, src)
}
func (m *MemberUpsertRequest) XXX_Size() int {
	return xxx_messageInfo_MemberUpsertRequest.Size(m)
}
func (m *MemberUpsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberUpsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MemberUpsertRequest proto.InternalMessageInfo

func (m *MemberUpsertRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MemberUpsertRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MemberUpsertRequest) GetMemberId() string {
	if m != nil {
		return m.MemberId
	}
	return ""
}

func (m *MemberUpsertRequest) GetMemberEmail() string {
	if m != nil {
		return m.MemberEmail
	}
	return ""
}

func (m *MemberUpsertRequest) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type MemberUpsertResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	MemberNumber         string   `protobuf:"bytes,2,opt,name=member_number,json=memberNumber,proto3" json:"member_number,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberUpsertResponse) Reset()         { *m = MemberUpsertResponse{} }
func (m *MemberUpsertResponse) String() string { return proto.CompactTextString(m) }
func (*MemberUpsertResponse) ProtoMessage()    {}
func (*MemberUpsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{5}
}

func (m *MemberUpsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberUpsertResponse.Unmarshal(m, b)
}
func (m *MemberUpsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberUpsertResponse.Marshal(b, m, deterministic)
}
func (m *MemberUpsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberUpsertResponse.Merge(m, src)
}
func (m *MemberUpsertResponse) XXX_Size() int {
	return xxx_messageInfo_MemberUpsertResponse.Size(m)
}
func (m *MemberUpsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberUpsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MemberUpsertResponse proto.InternalMessageInfo

func (m *MemberUpsertResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MemberUpsertResponse) GetMemberNumber() string {
	if m != nil {
		return m.MemberNumber
	}
	return ""
}

func (m *MemberUpsertResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type MemberDeleteRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	MemberNumber         string   `protobuf:"bytes,3,opt,name=member_number,json=memberNumber,proto3" json:"member_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberDeleteRequest) Reset()         { *m = MemberDeleteRequest{} }
func (m *MemberDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*MemberDeleteRequest) ProtoMessage()    {}
func (*MemberDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{6}
}

func (m *MemberDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberDeleteRequest.Unmarshal(m, b)
}
func (m *MemberDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberDeleteRequest.Marshal(b, m, deterministic)
}
func (m *MemberDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberDeleteRequest.Merge(m, src)
}
func (m *MemberDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_MemberDeleteRequest.Size(m)
}
func (m *MemberDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MemberDeleteRequest proto.InternalMessageInfo

func (m *MemberDeleteRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MemberDeleteRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MemberDeleteRequest) GetMemberNumber() string {
	if m != nil {
		return m.MemberNumber
	}
	return ""
}

type MemberDeleteResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Count                int64    `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MemberDeleteResponse) Reset()         { *m = MemberDeleteResponse{} }
func (m *MemberDeleteResponse) String() string { return proto.CompactTextString(m) }
func (*MemberDeleteResponse) ProtoMessage()    {}
func (*MemberDeleteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{7}
}

func (m *MemberDeleteResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MemberDeleteResponse.Unmarshal(m, b)
}
func (m *MemberDeleteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MemberDeleteResponse.Marshal(b, m, deterministic)
}
func (m *MemberDeleteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MemberDeleteResponse.Merge(m, src)
}
func (m *MemberDeleteResponse) XXX_Size() int {
	return xxx_messageInfo_MemberDeleteResponse.Size(m)
}
func (m *MemberDeleteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MemberDeleteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MemberDeleteResponse proto.InternalMessageInfo

func (m *MemberDeleteResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *MemberDeleteResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *MemberDeleteResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ProjectUpsertRequest struct {
	Project              *Project `protobuf:"bytes,1,opt,name=project,proto3" json:"project,omitempty"`
	Api                  string   `protobuf:"bytes,2,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectUpsertRequest) Reset()         { *m = ProjectUpsertRequest{} }
func (m *ProjectUpsertRequest) String() string { return proto.CompactTextString(m) }
func (*ProjectUpsertRequest) ProtoMessage()    {}
func (*ProjectUpsertRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{8}
}

func (m *ProjectUpsertRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectUpsertRequest.Unmarshal(m, b)
}
func (m *ProjectUpsertRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectUpsertRequest.Marshal(b, m, deterministic)
}
func (m *ProjectUpsertRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectUpsertRequest.Merge(m, src)
}
func (m *ProjectUpsertRequest) XXX_Size() int {
	return xxx_messageInfo_ProjectUpsertRequest.Size(m)
}
func (m *ProjectUpsertRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectUpsertRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectUpsertRequest proto.InternalMessageInfo

func (m *ProjectUpsertRequest) GetProject() *Project {
	if m != nil {
		return m.Project
	}
	return nil
}

func (m *ProjectUpsertRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ProjectUpsertRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ProjectUpsertResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProjectUpsertResponse) Reset()         { *m = ProjectUpsertResponse{} }
func (m *ProjectUpsertResponse) String() string { return proto.CompactTextString(m) }
func (*ProjectUpsertResponse) ProtoMessage()    {}
func (*ProjectUpsertResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{9}
}

func (m *ProjectUpsertResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProjectUpsertResponse.Unmarshal(m, b)
}
func (m *ProjectUpsertResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProjectUpsertResponse.Marshal(b, m, deterministic)
}
func (m *ProjectUpsertResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProjectUpsertResponse.Merge(m, src)
}
func (m *ProjectUpsertResponse) XXX_Size() int {
	return xxx_messageInfo_ProjectUpsertResponse.Size(m)
}
func (m *ProjectUpsertResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProjectUpsertResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProjectUpsertResponse proto.InternalMessageInfo

func (m *ProjectUpsertResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *ProjectUpsertResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetByTeamIdRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByTeamIdRequest) Reset()         { *m = GetByTeamIdRequest{} }
func (m *GetByTeamIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetByTeamIdRequest) ProtoMessage()    {}
func (*GetByTeamIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{10}
}

func (m *GetByTeamIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByTeamIdRequest.Unmarshal(m, b)
}
func (m *GetByTeamIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByTeamIdRequest.Marshal(b, m, deterministic)
}
func (m *GetByTeamIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByTeamIdRequest.Merge(m, src)
}
func (m *GetByTeamIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetByTeamIdRequest.Size(m)
}
func (m *GetByTeamIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByTeamIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByTeamIdRequest proto.InternalMessageInfo

func (m *GetByTeamIdRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetByTeamIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetByTeamIdResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Team                 *Team    `protobuf:"bytes,3,opt,name=team,proto3" json:"team,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByTeamIdResponse) Reset()         { *m = GetByTeamIdResponse{} }
func (m *GetByTeamIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetByTeamIdResponse) ProtoMessage()    {}
func (*GetByTeamIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{11}
}

func (m *GetByTeamIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByTeamIdResponse.Unmarshal(m, b)
}
func (m *GetByTeamIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByTeamIdResponse.Marshal(b, m, deterministic)
}
func (m *GetByTeamIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByTeamIdResponse.Merge(m, src)
}
func (m *GetByTeamIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetByTeamIdResponse.Size(m)
}
func (m *GetByTeamIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByTeamIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByTeamIdResponse proto.InternalMessageInfo

func (m *GetByTeamIdResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetByTeamIdResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetByTeamIdResponse) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *GetByTeamIdResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type GetByUserIdRequest struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByUserIdRequest) Reset()         { *m = GetByUserIdRequest{} }
func (m *GetByUserIdRequest) String() string { return proto.CompactTextString(m) }
func (*GetByUserIdRequest) ProtoMessage()    {}
func (*GetByUserIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{12}
}

func (m *GetByUserIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByUserIdRequest.Unmarshal(m, b)
}
func (m *GetByUserIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByUserIdRequest.Marshal(b, m, deterministic)
}
func (m *GetByUserIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByUserIdRequest.Merge(m, src)
}
func (m *GetByUserIdRequest) XXX_Size() int {
	return xxx_messageInfo_GetByUserIdRequest.Size(m)
}
func (m *GetByUserIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByUserIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByUserIdRequest proto.InternalMessageInfo

func (m *GetByUserIdRequest) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetByUserIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetByUserIdResponse struct {
	Api                  string   `protobuf:"bytes,1,opt,name=api,proto3" json:"api,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Team                 *Team    `protobuf:"bytes,3,opt,name=team,proto3" json:"team,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByUserIdResponse) Reset()         { *m = GetByUserIdResponse{} }
func (m *GetByUserIdResponse) String() string { return proto.CompactTextString(m) }
func (*GetByUserIdResponse) ProtoMessage()    {}
func (*GetByUserIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{13}
}

func (m *GetByUserIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByUserIdResponse.Unmarshal(m, b)
}
func (m *GetByUserIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByUserIdResponse.Marshal(b, m, deterministic)
}
func (m *GetByUserIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByUserIdResponse.Merge(m, src)
}
func (m *GetByUserIdResponse) XXX_Size() int {
	return xxx_messageInfo_GetByUserIdResponse.Size(m)
}
func (m *GetByUserIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByUserIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetByUserIdResponse proto.InternalMessageInfo

func (m *GetByUserIdResponse) GetApi() string {
	if m != nil {
		return m.Api
	}
	return ""
}

func (m *GetByUserIdResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetByUserIdResponse) GetTeam() *Team {
	if m != nil {
		return m.Team
	}
	return nil
}

func (m *GetByUserIdResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

type Team struct {
	Leader               string    `protobuf:"bytes,1,opt,name=leader,proto3" json:"leader,omitempty"`
	Members              []*Member `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	OpenRoles            int32     `protobuf:"varint,4,opt,name=open_roles,json=openRoles,proto3" json:"open_roles,omitempty"`
	Skills               []string  `protobuf:"bytes,5,rep,name=skills,proto3" json:"skills,omitempty"`
	Size                 int32     `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	LastActive           int32     `protobuf:"varint,7,opt,name=last_active,json=lastActive,proto3" json:"last_active,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Team) Reset()         { *m = Team{} }
func (m *Team) String() string { return proto.CompactTextString(m) }
func (*Team) ProtoMessage()    {}
func (*Team) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{14}
}

func (m *Team) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Team.Unmarshal(m, b)
}
func (m *Team) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Team.Marshal(b, m, deterministic)
}
func (m *Team) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Team.Merge(m, src)
}
func (m *Team) XXX_Size() int {
	return xxx_messageInfo_Team.Size(m)
}
func (m *Team) XXX_DiscardUnknown() {
	xxx_messageInfo_Team.DiscardUnknown(m)
}

var xxx_messageInfo_Team proto.InternalMessageInfo

func (m *Team) GetLeader() string {
	if m != nil {
		return m.Leader
	}
	return ""
}

func (m *Team) GetMembers() []*Member {
	if m != nil {
		return m.Members
	}
	return nil
}

func (m *Team) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Team) GetOpenRoles() int32 {
	if m != nil {
		return m.OpenRoles
	}
	return 0
}

func (m *Team) GetSkills() []string {
	if m != nil {
		return m.Skills
	}
	return nil
}

func (m *Team) GetSize() int32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *Team) GetLastActive() int32 {
	if m != nil {
		return m.LastActive
	}
	return 0
}

type Member struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Id                   int32    `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	Role                 string   `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Member) Reset()         { *m = Member{} }
func (m *Member) String() string { return proto.CompactTextString(m) }
func (*Member) ProtoMessage()    {}
func (*Member) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{15}
}

func (m *Member) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Member.Unmarshal(m, b)
}
func (m *Member) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Member.Marshal(b, m, deterministic)
}
func (m *Member) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Member.Merge(m, src)
}
func (m *Member) XXX_Size() int {
	return xxx_messageInfo_Member.Size(m)
}
func (m *Member) XXX_DiscardUnknown() {
	xxx_messageInfo_Member.DiscardUnknown(m)
}

var xxx_messageInfo_Member proto.InternalMessageInfo

func (m *Member) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Member) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Member) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

type Project struct {
	Description          string   `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Languages            []string `protobuf:"bytes,2,rep,name=languages,proto3" json:"languages,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	GithubLink           string   `protobuf:"bytes,4,opt,name=github_link,json=githubLink,proto3" json:"github_link,omitempty"`
	Complexity           int32    `protobuf:"varint,5,opt,name=complexity,proto3" json:"complexity,omitempty"`
	Duration             int32    `protobuf:"varint,6,opt,name=duration,proto3" json:"duration,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Project) Reset()         { *m = Project{} }
func (m *Project) String() string { return proto.CompactTextString(m) }
func (*Project) ProtoMessage()    {}
func (*Project) Descriptor() ([]byte, []int) {
	return fileDescriptor_8b4e9e93d7b2c6bb, []int{16}
}

func (m *Project) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Project.Unmarshal(m, b)
}
func (m *Project) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Project.Marshal(b, m, deterministic)
}
func (m *Project) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Project.Merge(m, src)
}
func (m *Project) XXX_Size() int {
	return xxx_messageInfo_Project.Size(m)
}
func (m *Project) XXX_DiscardUnknown() {
	xxx_messageInfo_Project.DiscardUnknown(m)
}

var xxx_messageInfo_Project proto.InternalMessageInfo

func (m *Project) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Project) GetLanguages() []string {
	if m != nil {
		return m.Languages
	}
	return nil
}

func (m *Project) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Project) GetGithubLink() string {
	if m != nil {
		return m.GithubLink
	}
	return ""
}

func (m *Project) GetComplexity() int32 {
	if m != nil {
		return m.Complexity
	}
	return 0
}

func (m *Project) GetDuration() int32 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func init() {
	proto.RegisterType((*TeamUpsertRequest)(nil), "team.TeamUpsertRequest")
	proto.RegisterType((*TeamUpsertResponse)(nil), "team.TeamUpsertResponse")
	proto.RegisterType((*TeamDeleteRequest)(nil), "team.TeamDeleteRequest")
	proto.RegisterType((*TeamDeleteResponse)(nil), "team.TeamDeleteResponse")
	proto.RegisterType((*MemberUpsertRequest)(nil), "team.MemberUpsertRequest")
	proto.RegisterType((*MemberUpsertResponse)(nil), "team.MemberUpsertResponse")
	proto.RegisterType((*MemberDeleteRequest)(nil), "team.MemberDeleteRequest")
	proto.RegisterType((*MemberDeleteResponse)(nil), "team.MemberDeleteResponse")
	proto.RegisterType((*ProjectUpsertRequest)(nil), "team.ProjectUpsertRequest")
	proto.RegisterType((*ProjectUpsertResponse)(nil), "team.ProjectUpsertResponse")
	proto.RegisterType((*GetByTeamIdRequest)(nil), "team.GetByTeamIdRequest")
	proto.RegisterType((*GetByTeamIdResponse)(nil), "team.GetByTeamIdResponse")
	proto.RegisterType((*GetByUserIdRequest)(nil), "team.GetByUserIdRequest")
	proto.RegisterType((*GetByUserIdResponse)(nil), "team.GetByUserIdResponse")
	proto.RegisterType((*Team)(nil), "team.Team")
	proto.RegisterType((*Member)(nil), "team.Member")
	proto.RegisterType((*Project)(nil), "team.Project")
}

func init() { proto.RegisterFile("team.proto", fileDescriptor_8b4e9e93d7b2c6bb) }

var fileDescriptor_8b4e9e93d7b2c6bb = []byte{
	// 1034 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0x4f, 0x6f, 0xdc, 0x44,
	0x14, 0x97, 0xd7, 0xbb, 0x49, 0xf7, 0x6d, 0x1a, 0xd2, 0x49, 0x48, 0x37, 0x9b, 0xd2, 0x6c, 0x5d,
	0xd4, 0x46, 0x11, 0x59, 0xb7, 0x4b, 0xcb, 0x21, 0x27, 0x92, 0x52, 0x55, 0x95, 0xa0, 0x42, 0xa6,
	0x01, 0x0e, 0x48, 0xd1, 0xac, 0xfd, 0xb4, 0xeb, 0xc6, 0xeb, 0x31, 0x9e, 0x71, 0xda, 0x10, 0xe5,
	0xc2, 0x95, 0x1b, 0x48, 0x1c, 0xf8, 0x26, 0x20, 0x71, 0xe5, 0x0b, 0x70, 0xe2, 0xce, 0x07, 0x41,
	0x7e, 0x33, 0x4e, 0xec, 0xac, 0xa3, 0x12, 0x21, 0x4e, 0x3b, 0xf3, 0xde, 0xcc, 0xfb, 0xfd, 0xde,
	0x9f, 0xf9, 0x79, 0x01, 0x14, 0xf2, 0xe9, 0x20, 0x49, 0x85, 0x12, 0xac, 0x99, 0xaf, 0x7b, 0xb7,
	0xc6, 0x42, 0x8c, 0x23, 0x74, 0x79, 0x12, 0xba, 0x3c, 0x8e, 0x85, 0xe2, 0x2a, 0x14, 0xb1, 0xd4,
	0x67, 0x7a, 0x1f, 0xd0, 0x8f, 0xbf, 0x3d, 0xc6, 0x78, 0x5b, 0xbe, 0xe6, 0xe3, 0x31, 0xa6, 0xae,
	0x48, 0xe8, 0xc4, 0xec, 0x69, 0xe7, 0x29, 0xdc, 0x78, 0x89, 0x7c, 0xba, 0x9f, 0x48, 0x4c, 0x95,
	0x87, 0xdf, 0x66, 0x28, 0x15, 0x5b, 0x02, 0x9b, 0x27, 0x61, 0xd7, 0xea, 0x5b, 0x9b, 0x6d, 0x2f,
	0x5f, 0xb2, 0xdb, 0x40, 0xd0, 0xdd, 0x46, 0xdf, 0xda, 0xec, 0x0c, 0x61, 0x40, 0x9c, 0xf2, 0x8b,
	0x1e, 0xd9, 0x9d, 0x17, 0xc0, 0xca, 0x61, 0x64, 0x22, 0x62, 0x89, 0x35, 0x71, 0x56, 0x61, 0x4e,
	0x2a, 0xae, 0x32, 0x49, 0x91, 0xda, 0x9e, 0xd9, 0xb1, 0x45, 0x68, 0x84, 0x41, 0xd7, 0x26, 0x5b,
	0x23, 0x0c, 0x9c, 0xc7, 0x9a, 0xd6, 0x27, 0x18, 0xa1, 0xc2, 0xcb, 0x69, 0xe9, 0x6b, 0x8d, 0xb3,
	0x6b, 0x3f, 0x5b, 0x9a, 0x47, 0x71, 0xef, 0xca, 0x3c, 0x56, 0xa0, 0x95, 0xe7, 0x23, 0x89, 0x8a,
	0xed, 0xe9, 0x0d, 0xeb, 0xc2, 0xfc, 0x14, 0xa7, 0x23, 0x4c, 0x65, 0xb7, 0x49, 0xf6, 0x62, 0x4b,
	0x71, 0x0e, 0xc3, 0x28, 0x92, 0xdd, 0x16, 0x39, 0xcc, 0xce, 0x10, 0x9b, 0x3b, 0x23, 0xf6, 0x83,
	0x05, 0xcb, 0x9f, 0xd1, 0x9d, 0xb7, 0x55, 0xfa, 0x42, 0x4a, 0x6c, 0x1d, 0xda, 0x1a, 0xec, 0xe0,
	0xac, 0x40, 0xd7, 0xb4, 0xe1, 0x79, 0xc0, 0xee, 0xc0, 0x82, 0x71, 0xe2, 0x94, 0x87, 0x11, 0xb1,
	0x6b, 0x7b, 0x1d, 0x6d, 0x7b, 0x9a, 0x9b, 0x18, 0x83, 0x66, 0x2a, 0x22, 0x24, 0x7e, 0x6d, 0x8f,
	0xd6, 0x0e, 0xc2, 0x4a, 0x95, 0xcc, 0xa5, 0x75, 0xba, 0x0b, 0xd7, 0x0d, 0x40, 0x9c, 0xe5, 0x3f,
	0x86, 0x98, 0x41, 0x7d, 0x41, 0xb6, 0x52, 0x31, 0xed, 0x72, 0x31, 0x9d, 0x6f, 0x8a, 0x9c, 0xaf,
	0xd8, 0xc6, 0x59, 0x54, 0x7b, 0x16, 0xd5, 0xf9, 0xb2, 0x48, 0xe2, 0xbf, 0x34, 0xdb, 0x17, 0x59,
	0xac, 0x8a, 0x66, 0xd3, 0xc6, 0xe1, 0xb0, 0xf2, 0x79, 0x2a, 0x5e, 0xa1, 0xaf, 0xaa, 0xad, 0xba,
	0x0f, 0xf3, 0x89, 0xb6, 0x53, 0xec, 0xce, 0xf0, 0xba, 0x7e, 0x05, 0xe6, 0xb0, 0x57, 0x78, 0x0b,
	0x02, 0x8d, 0x8b, 0xf9, 0x9d, 0x4f, 0xf7, 0x2e, 0xbc, 0x7b, 0x01, 0xe2, 0xaa, 0xdc, 0x9d, 0x8f,
	0x80, 0x3d, 0x43, 0xb5, 0x77, 0x9c, 0x4f, 0xfb, 0xf3, 0xe0, 0xdf, 0xbf, 0x10, 0x01, 0xcb, 0x95,
	0x7b, 0x97, 0x02, 0x5f, 0xec, 0x49, 0xa1, 0x00, 0x76, 0xbd, 0x02, 0x94, 0x88, 0x36, 0x6b, 0x89,
	0xee, 0xcb, 0x7c, 0x62, 0xaf, 0x4e, 0xb4, 0xb8, 0xf7, 0xbf, 0x13, 0xfd, 0xc3, 0x82, 0xe6, 0x4b,
	0x73, 0x20, 0x42, 0x1e, 0x60, 0x6a, 0x50, 0xcc, 0x8e, 0xdd, 0x3b, 0x57, 0x81, 0x46, 0xdf, 0xde,
	0xec, 0x0c, 0x17, 0x74, 0x6c, 0x3d, 0x85, 0xe7, 0x9a, 0xc0, 0xa0, 0x19, 0xf3, 0x29, 0x9a, 0x7e,
	0xd3, 0x9a, 0xbd, 0x07, 0x20, 0x12, 0x8c, 0x0f, 0xf2, 0xe7, 0xa7, 0x81, 0x5b, 0x5e, 0x3b, 0xb7,
	0x78, 0xb9, 0xa1, 0x22, 0x23, 0x36, 0x71, 0xd2, 0x32, 0xc2, 0xa0, 0x29, 0xc3, 0xef, 0x90, 0x84,
	0xa4, 0xe5, 0xd1, 0x9a, 0x6d, 0x40, 0x27, 0xe2, 0x52, 0x1d, 0x70, 0x5f, 0x85, 0x47, 0xd8, 0x9d,
	0x27, 0x17, 0xe4, 0xa6, 0x5d, 0xb2, 0x38, 0x7b, 0x30, 0xa7, 0x29, 0xe5, 0x03, 0xae, 0x75, 0x41,
	0x27, 0xa2, 0x37, 0xa5, 0x82, 0xb5, 0xa8, 0x60, 0x85, 0x42, 0xd8, 0x25, 0x85, 0xf8, 0xcd, 0x82,
	0x79, 0x33, 0xa2, 0xac, 0x0f, 0x9d, 0x00, 0xa5, 0x9f, 0x86, 0xf4, 0x11, 0x31, 0xb1, 0xca, 0x26,
	0x76, 0x0b, 0xda, 0x11, 0x8f, 0xc7, 0x19, 0x1f, 0xa3, 0xae, 0x4d, 0xdb, 0x3b, 0x37, 0xd4, 0xd6,
	0x63, 0x03, 0x3a, 0xe3, 0x50, 0x4d, 0xb2, 0xd1, 0x41, 0x14, 0xc6, 0x87, 0xa6, 0x13, 0xa0, 0x4d,
	0x9f, 0x86, 0xf1, 0x21, 0xbb, 0x0d, 0xe0, 0x8b, 0x69, 0x12, 0xe1, 0x9b, 0x50, 0x1d, 0x93, 0x78,
	0xb5, 0xbc, 0x92, 0x85, 0xf5, 0xe0, 0x5a, 0x90, 0xa5, 0xf4, 0x29, 0x33, 0xd5, 0x39, 0xdb, 0x0f,
	0xff, 0x6a, 0x41, 0x27, 0xef, 0xe4, 0x17, 0x98, 0x1e, 0x85, 0x3e, 0xb2, 0x7d, 0x80, 0x27, 0x29,
	0x72, 0x85, 0xd4, 0xde, 0x9b, 0xe7, 0x13, 0x51, 0x79, 0xe0, 0xbd, 0xee, 0xac, 0x43, 0x0f, 0x9d,
	0xb3, 0xf2, 0xfd, 0x9f, 0x7f, 0xff, 0xd4, 0x58, 0x74, 0xda, 0xee, 0xd1, 0x43, 0x97, 0x3e, 0x09,
	0x3b, 0xd6, 0x16, 0xfb, 0x0a, 0x40, 0x4b, 0xcf, 0xc5, 0xb0, 0x15, 0xb9, 0x2b, 0x87, 0xad, 0x2a,
	0x95, 0xb3, 0x4a, 0x61, 0x97, 0xb6, 0x16, 0xcf, 0xc2, 0xba, 0x27, 0x61, 0x70, 0xca, 0x10, 0xda,
	0xbb, 0x41, 0x60, 0x7a, 0xb8, 0x56, 0x1e, 0xb2, 0x2a, 0xe1, 0x5e, 0x9d, 0xcb, 0xc4, 0xbe, 0x43,
	0xb1, 0xd7, 0x9d, 0xd5, 0x6a, 0x6c, 0xd7, 0x0c, 0x69, 0xce, 0x3f, 0x83, 0x05, 0x0f, 0xa7, 0xe2,
	0x08, 0xeb, 0x90, 0xaa, 0x39, 0xf4, 0xea, 0x5c, 0x06, 0x69, 0x40, 0x48, 0x9b, 0x5b, 0xf7, 0xea,
	0x91, 0xdc, 0x93, 0x8a, 0x94, 0x9f, 0x32, 0x01, 0x37, 0x34, 0xd7, 0xbc, 0x22, 0xc5, 0x8c, 0xf5,
	0x2a, 0x5a, 0x5a, 0x4d, 0x73, 0xbd, 0xd6, 0xf7, 0x96, 0x3c, 0x8d, 0x18, 0xe7, 0x79, 0x72, 0x78,
	0xe7, 0x19, 0x12, 0x5a, 0x21, 0x7b, 0xcc, 0xf4, 0x64, 0x56, 0x41, 0x7b, 0x6b, 0x35, 0x1e, 0x03,
	0xb5, 0x46, 0x50, 0xcb, 0xec, 0x86, 0x7b, 0xc2, 0x93, 0xf0, 0xb4, 0xdc, 0xb1, 0x09, 0x2c, 0x19,
	0x08, 0x59, 0x28, 0x56, 0x05, 0xa3, 0x22, 0x7e, 0x15, 0x8c, 0xaa, 0xbc, 0x39, 0x1b, 0x84, 0xb1,
	0xc6, 0x6e, 0x56, 0x30, 0x32, 0x49, 0x85, 0x0c, 0x83, 0xd3, 0xbd, 0xdf, 0xad, 0x1f, 0x77, 0x7f,
	0xb5, 0xd8, 0xd7, 0xb0, 0x90, 0xbb, 0xfa, 0x52, 0x8f, 0xb8, 0xf3, 0xa4, 0xba, 0x67, 0x77, 0x27,
	0x4a, 0x25, 0x72, 0xc7, 0x75, 0xf5, 0x93, 0x1a, 0xf8, 0x62, 0xea, 0xfa, 0x87, 0xa3, 0x11, 0x8f,
	0x22, 0x37, 0xc0, 0xa3, 0x6d, 0xfa, 0x1f, 0xb9, 0x38, 0x8a, 0xf8, 0xe4, 0xe3, 0x09, 0x4f, 0x92,
	0xe3, 0x81, 0x48, 0xc7, 0x43, 0xfb, 0xe1, 0xe0, 0xc1, 0x56, 0xc3, 0x6a, 0x0c, 0x97, 0x78, 0x92,
	0x44, 0xa1, 0x4f, 0xaf, 0xc9, 0x7d, 0x25, 0x45, 0xbc, 0x33, 0x63, 0xf1, 0x1e, 0x83, 0xfd, 0xe8,
	0xc1, 0x23, 0x36, 0x80, 0xf7, 0x3d, 0x54, 0x59, 0x1a, 0x63, 0xd0, 0x7f, 0x3d, 0xc1, 0xb8, 0x9f,
	0xa2, 0x14, 0x59, 0xea, 0x63, 0x3f, 0x10, 0x28, 0xe3, 0xfb, 0xaa, 0x8f, 0x6f, 0x42, 0xa9, 0xd8,
	0x1c, 0x34, 0x7f, 0x69, 0x58, 0xf3, 0xa3, 0x39, 0xfa, 0xdb, 0xf9, 0xe1, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x3b, 0x55, 0x95, 0x81, 0xd6, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TeamServiceClient is the client API for TeamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TeamServiceClient interface {
	CreateTeam(ctx context.Context, in *TeamUpsertRequest, opts ...grpc.CallOption) (*TeamUpsertResponse, error)
	DeleteTeam(ctx context.Context, in *TeamDeleteRequest, opts ...grpc.CallOption) (*TeamDeleteResponse, error)
	AddMember(ctx context.Context, in *MemberUpsertRequest, opts ...grpc.CallOption) (*MemberUpsertResponse, error)
	RemoveMember(ctx context.Context, in *MemberDeleteRequest, opts ...grpc.CallOption) (*MemberDeleteResponse, error)
	UpsertTeamProject(ctx context.Context, in *ProjectUpsertRequest, opts ...grpc.CallOption) (*ProjectUpsertResponse, error)
	GetTeamByTeamId(ctx context.Context, in *GetByTeamIdRequest, opts ...grpc.CallOption) (*GetByTeamIdResponse, error)
	GetTeamsByUserId(ctx context.Context, in *GetByUserIdRequest, opts ...grpc.CallOption) (*GetByUserIdResponse, error)
}

type teamServiceClient struct {
	cc *grpc.ClientConn
}

func NewTeamServiceClient(cc *grpc.ClientConn) TeamServiceClient {
	return &teamServiceClient{cc}
}

func (c *teamServiceClient) CreateTeam(ctx context.Context, in *TeamUpsertRequest, opts ...grpc.CallOption) (*TeamUpsertResponse, error) {
	out := new(TeamUpsertResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/CreateTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) DeleteTeam(ctx context.Context, in *TeamDeleteRequest, opts ...grpc.CallOption) (*TeamDeleteResponse, error) {
	out := new(TeamDeleteResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/DeleteTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) AddMember(ctx context.Context, in *MemberUpsertRequest, opts ...grpc.CallOption) (*MemberUpsertResponse, error) {
	out := new(MemberUpsertResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/AddMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) RemoveMember(ctx context.Context, in *MemberDeleteRequest, opts ...grpc.CallOption) (*MemberDeleteResponse, error) {
	out := new(MemberDeleteResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/RemoveMember", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) UpsertTeamProject(ctx context.Context, in *ProjectUpsertRequest, opts ...grpc.CallOption) (*ProjectUpsertResponse, error) {
	out := new(ProjectUpsertResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/UpsertTeamProject", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) GetTeamByTeamId(ctx context.Context, in *GetByTeamIdRequest, opts ...grpc.CallOption) (*GetByTeamIdResponse, error) {
	out := new(GetByTeamIdResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/GetTeamByTeamId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *teamServiceClient) GetTeamsByUserId(ctx context.Context, in *GetByUserIdRequest, opts ...grpc.CallOption) (*GetByUserIdResponse, error) {
	out := new(GetByUserIdResponse)
	err := c.cc.Invoke(ctx, "/team.TeamService/GetTeamsByUserId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeamServiceServer is the server API for TeamService service.
type TeamServiceServer interface {
	CreateTeam(context.Context, *TeamUpsertRequest) (*TeamUpsertResponse, error)
	DeleteTeam(context.Context, *TeamDeleteRequest) (*TeamDeleteResponse, error)
	AddMember(context.Context, *MemberUpsertRequest) (*MemberUpsertResponse, error)
	RemoveMember(context.Context, *MemberDeleteRequest) (*MemberDeleteResponse, error)
	UpsertTeamProject(context.Context, *ProjectUpsertRequest) (*ProjectUpsertResponse, error)
	GetTeamByTeamId(context.Context, *GetByTeamIdRequest) (*GetByTeamIdResponse, error)
	GetTeamsByUserId(context.Context, *GetByUserIdRequest) (*GetByUserIdResponse, error)
}

// UnimplementedTeamServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTeamServiceServer struct {
}

func (*UnimplementedTeamServiceServer) CreateTeam(ctx context.Context, req *TeamUpsertRequest) (*TeamUpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeam not implemented")
}
func (*UnimplementedTeamServiceServer) DeleteTeam(ctx context.Context, req *TeamDeleteRequest) (*TeamDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTeam not implemented")
}
func (*UnimplementedTeamServiceServer) AddMember(ctx context.Context, req *MemberUpsertRequest) (*MemberUpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMember not implemented")
}
func (*UnimplementedTeamServiceServer) RemoveMember(ctx context.Context, req *MemberDeleteRequest) (*MemberDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveMember not implemented")
}
func (*UnimplementedTeamServiceServer) UpsertTeamProject(ctx context.Context, req *ProjectUpsertRequest) (*ProjectUpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertTeamProject not implemented")
}
func (*UnimplementedTeamServiceServer) GetTeamByTeamId(ctx context.Context, req *GetByTeamIdRequest) (*GetByTeamIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamByTeamId not implemented")
}
func (*UnimplementedTeamServiceServer) GetTeamsByUserId(ctx context.Context, req *GetByUserIdRequest) (*GetByUserIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTeamsByUserId not implemented")
}

func RegisterTeamServiceServer(s *grpc.Server, srv TeamServiceServer) {
	s.RegisterService(&_TeamService_serviceDesc, srv)
}

func _TeamService_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeamUpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/CreateTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).CreateTeam(ctx, req.(*TeamUpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_DeleteTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeamDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).DeleteTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/DeleteTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).DeleteTeam(ctx, req.(*TeamDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_AddMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberUpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).AddMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/AddMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).AddMember(ctx, req.(*MemberUpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_RemoveMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemberDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).RemoveMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/RemoveMember",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).RemoveMember(ctx, req.(*MemberDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_UpsertTeamProject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProjectUpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).UpsertTeamProject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/UpsertTeamProject",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).UpsertTeamProject(ctx, req.(*ProjectUpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_GetTeamByTeamId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByTeamIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).GetTeamByTeamId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/GetTeamByTeamId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).GetTeamByTeamId(ctx, req.(*GetByTeamIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TeamService_GetTeamsByUserId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByUserIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeamServiceServer).GetTeamsByUserId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/team.TeamService/GetTeamsByUserId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeamServiceServer).GetTeamsByUserId(ctx, req.(*GetByUserIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _TeamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "team.TeamService",
	HandlerType: (*TeamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTeam",
			Handler:    _TeamService_CreateTeam_Handler,
		},
		{
			MethodName: "DeleteTeam",
			Handler:    _TeamService_DeleteTeam_Handler,
		},
		{
			MethodName: "AddMember",
			Handler:    _TeamService_AddMember_Handler,
		},
		{
			MethodName: "RemoveMember",
			Handler:    _TeamService_RemoveMember_Handler,
		},
		{
			MethodName: "UpsertTeamProject",
			Handler:    _TeamService_UpsertTeamProject_Handler,
		},
		{
			MethodName: "GetTeamByTeamId",
			Handler:    _TeamService_GetTeamByTeamId_Handler,
		},
		{
			MethodName: "GetTeamsByUserId",
			Handler:    _TeamService_GetTeamsByUserId_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "team.proto",
}
